// Canonical list of Israeli cities used for the tutor profile dropdown.
// Keeping it fixed (vs free text) keeps the city filter consistent.
// Sorted alphabetically. Spellings here must match seed data.
export const CITIES = [
  'Acre',
  'Afula',
  'Arad',
  'Ashdod',
  'Ashkelon',
  "Be'er Sheva",
  "Be'er Ya'akov",
  'Beit Shemesh',
  "Beit She'an",
  'Bat Yam',
  'Bnei Brak',
  'Dimona',
  'Eilat',
  'Gan Yavne',
  'Givatayim',
  'Hadera',
  'Haifa',
  'Herzliya',
  'Hod HaSharon',
  'Holon',
  'Jerusalem',
  'Karmiel',
  'Kfar Saba',
  'Kfar Yona',
  'Kiryat Ata',
  'Kiryat Bialik',
  'Kiryat Gat',
  'Kiryat Motzkin',
  'Kiryat Ono',
  'Kiryat Shmona',
  'Kiryat Yam',
  'Lod',
  'Ma\'alot-Tarshiha',
  'Migdal HaEmek',
  "Modi'in",
  'Nahariya',
  'Nazareth',
  'Nesher',
  'Ness Ziona',
  'Netanya',
  'Netivot',
  'Or Yehuda',
  'Ofakim',
  'Petah Tikva',
  "Ra'anana",
  'Ramat Gan',
  'Ramla',
  'Rehovot',
  'Rishon LeZion',
  'Rosh HaAyin',
  'Safed',
  'Sderot',
  "Shfar'am",
  'Tel Aviv',
  'Tiberias',
  'Tirat Carmel',
  'Yavne',
  'Yokneam',
] as const
